version: '3.7'

services:

  my-app:
    container_name: my-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '8081:8080'
    # run in development mode
    command: npm run serve
    stdin_open: true
    tty: true

    environment:
      - CHOKIDAR_USEPOLLING=true
      
